steps:

# FRONTEND

- id: 'frontend-build'
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', 'frontend']

- id: 'frontend-push'
  waitFor: ['frontend-build']
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']

# BACKEND

- id: 'backend-build'
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA', 'backend']

- id: 'backend-push'
  waitFor: ['backend-build']
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']

# DEPLOYMENT

- waitFor: ['frontend-push', 'backend-push']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - -c
  - |
    gcloud config set compute/zone us-east1-d
    CLOUDSDK_CORE_DISABLE_PROMPTS=1 scripts/deploy $COMMIT_SHA
