# Inspiration:
# https://goo.gl/n1q5Gf
# https://goo.gl/HzrrFa

version: '3'
services:

  frontend:
    image: gcr.io/digital-seat-198720/frontend:$COMMIT_SHA
    depends_on:
    - nginx-letsencrypt
    environment:
    - VIRTUAL_HOST=legacy.auzom.gg
    - LETSENCRYPT_HOST=legacy.auzom.gg
    - LETSENCRYPT_EMAIL=admin@auzom.gg
    restart: unless-stopped

  postgres:
    image: postgres:$POSTGRES_VERSION
    volumes:
    - /mnt/disks/data/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  backend:
    image: gcr.io/digital-seat-198720/backend:$COMMIT_SHA
    depends_on:
    - nginx-letsencrypt
    - postgres
    environment:
    - VIRTUAL_HOST=api.legacy.auzom.gg
    - LETSENCRYPT_HOST=api.legacy.auzom.gg
    - LETSENCRYPT_EMAIL=admin@auzom.gg
    - STATIC_HOST=legacy.auzom.gg
    - POSTGRES_URL=$POSTGRES_URL
    env_file: .secrets
    command: serve
    restart: unless-stopped

  worker:
    image: gcr.io/digital-seat-198720/backend:$COMMIT_SHA
    depends_on:
    - postgres
    environment:
    - STATIC_HOST=legacy.auzom.gg
    - POSTGRES_URL=$POSTGRES_URL
    env_file: .secrets
    command: work
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    labels: [com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy]
    volumes:
    - confd:/etc/nginx/conf.d
    - vhostd:/etc/nginx/vhost.d
    - html:/usr/share/nginx/html
    - certs:/etc/nginx/certs:ro
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped

  nginx-gen:
    image: jwilder/docker-gen
    depends_on:
    - nginx
    labels: [com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen]
    volumes:
    - confd:/etc/nginx/conf.d
    - vhostd:/etc/nginx/vhost.d
    - html:/usr/share/nginx/html
    - certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    entrypoint: []
    command:
    - sh
    - -c
    - |
      wget https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl
      docker-gen \
        -notify-sighup nginx \
        -watch \
        -wait 5s:30s \
        nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
    - nginx-gen
    volumes:
    - confd:/etc/nginx/conf.d
    - vhostd:/etc/nginx/vhost.d
    - html:/usr/share/nginx/html
    - certs:/etc/nginx/certs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  confd:
  vhostd:
  html:
  certs:
