version: '3'
services:

  frontend:
    image: node:8
    working_dir: /app
    expose:
    - 80
    volumes:
    - ./frontend:/app
    environment:
    - FORCE_COLOR=1
    ports: 
    - 3000:80
    command: bash -c 'yarn --frozen-lockfile && yarn start; sleep infinity'

  postgres:
    image: postgres:$POSTGRES_VERSION # Comes from .env
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432

  backend: &backend
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
    - ./backend:/go/src/app
    depends_on: # `links` originally, isn't passed by `extends`, just in case
    - postgres
    environment:
    - STATIC_HOST=localhost:3000
    - FORCE_COLOR=1
    - POSTGRES_URL=$POSTGRES_URL
    ports:
    - 3001:80
    command: bash -c 'yarn --frozen-lockfile && gulp; sleep infinity'

  worker:
    <<: *backend
    ports: []
    command: bash -c 'yarn --frozen-lockfile && gulp worker; sleep infinity'

  pgweb:
    image: sosedoff/pgweb
    depends_on:
    - postgres
    environment:
    - DATABASE_URL=$POSTGRES_URL
    ports: 
    - 3002:8081
    restart: unless-stopped
