version: '3'
services:

  nginx:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/robots.txt:/robots.txt:ro
    depends_on: # `links` originally
    - backend
    - frontend
    ports:
    - 0.0.0.0:3000:80

  backend-common: &backend-common
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
    - ./backend:/go/src/app
    - ./migrations:/migrations
    depends_on: # `links` originally, isn't passed by `extends`, just in case
    - postgres
    env_file: backend/.env.local
    environment:
    - FORCE_COLOR=1
    - POSTGRES_SSLMODE=disable
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DBNAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  backend:
    <<: *backend-common # makeshift `extends`
    command: bash -c 'yarn --pure-lockfile && gulp; sleep infinity'

  worker:
    <<: *backend-common
    command: bash -c 'yarn --pure-lockfile && gulp worker; sleep infinity'

  frontend:
    image: node:8
    working_dir: /app
    expose:
    - 80
    volumes:
    - ./frontend:/app
    environment:
    - FORCE_COLOR=1
    command: bash -c 'yarn --pure-lockfile && yarn start; sleep infinity'

  postgres:
    image: postgres:${POSTGRES_VERSION} # comes from .env
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - 127.0.0.1:5432:5432
